/* ── Basel Supper Club — rendering, router, booking form ──
   Reads window.SITE (content.js) and window.IMAGES (generated by build.mjs). */
(function () {
  "use strict";

  var S = window.SITE;
  var P_DINNER = S.P_DINNER, P_DRINKS = S.P_DRINKS;
  var CUISINES = S.CUISINES, FLAGS = S.FLAGS, EVENINGS = S.EVENINGS;
  var TIMELINE = S.TIMELINE, FAQ = S.FAQ, GALLERY = S.GALLERY, ICONS = S.ICONS;
  var PAST = S.PAST || [], REVIEWS = S.REVIEWS || [];

  /* Menu dishes reference a photo by its filename stem, so dropping
     "gajar ka halwa.png" into assets/gallery/food is all it takes. */
  var FOOD_BY_STEM = (function(){
    var m = {}, list = (window.GALLERIES && window.GALLERIES.food) || [];
    list.forEach(function(it){ if(it.stem) m[it.stem] = it; });
    return m;
  })();

  function dishHTML(d){
    var name = typeof d === "string" ? d : d.name;
    var pic  = typeof d === "string" ? null : FOOD_BY_STEM[(d.photo||"").toLowerCase()];
    return '<li class="dish">' +
      '<span class="dish-pic-wrap">' +
      (pic ? '<img class="dish-pic" src="'+pic.thumb+'" alt="'+name+'" loading="lazy" decoding="async">'
           : '<span class="dish-pic none" aria-hidden="true"></span>') +
      '</span><span class="dish-name">'+name+'</span></li>';
  }
  function menuHTML(menu){
    return menu.map(function(g){
      return '<li class="group"><div class="course-name">'+g.course+'</div>'+
             '<ul class="dish-list">'+g.dishes.map(dishHTML).join("")+'</ul></li>';
    }).join("");
  }

  var $ = function(s,r){ return (r||document).querySelector(s); };
  var $$ = function(s,r){ return Array.prototype.slice.call((r||document).querySelectorAll(s)); };
  function el(t,c,h){ var n=document.createElement(t); if(c)n.className=c; if(h!=null)n.innerHTML=h; return n; }
  function chf(n){ return "CHF "+n.toLocaleString("de-CH"); }
  function plain(s){ return s.replace(/&amp;/g,"&"); }
  function svg(p,cls){ return '<svg class="ic '+(cls||"")+'" viewBox="0 0 24 24">'+p+'</svg>'; }

  /* ---- host portraits: assets/gallery/hosts/{together,nik,ania} ---- */
  (function(){
    var H = window.HOSTS || {};
    $$("[data-host]").forEach(function(img){
      var key = img.getAttribute("data-host");
      if (H[key]) {
        img.src = H[key];
        img.loading = "lazy";
        var slot = img.closest("[data-hostslot]");
        if (slot) { var ph = $(".ph", slot); if (ph) ph.remove(); }
      } else if (!img.hasAttribute("data-img")) {
        img.remove();                 // no file yet — leave the placeholder
      }
    });
  })();

  /* ---- wire up the photos ---- */
  $$("[data-img]").forEach(function(n){
    var k = n.getAttribute("data-img");
    if (IMAGES[k]) { n.src = IMAGES[k]; n.loading = "lazy"; }
  });
  $$("[data-bg]").forEach(function(n){
    var k = n.getAttribute("data-bg");
    if (IMAGES[k]) n.style.backgroundImage = 'url("'+IMAGES[k]+'")';
  });

  /* ---- marquee ---- */
  (function(){
    var words = ["Ramen","Tantan","Curry","Gyoza","Pasta","Thai","Tacos","Paneer","Dumplings","Chilli oil","Mezze","Ragù"];
    var run = words.map(function(w){ return '<span>'+w+'<i></i></span>'; }).join("");
    $("#marq").innerHTML = run + run;
  })();

  /* ---- stats ---- */
  (function(){
    var S=[["6–8","Seats at the table"],["40+","Countries on the menu"],["120","CHF per person"],["1","Long table"]];
    var box=$("#stats");
    S.forEach(function(s){ box.appendChild(el("div","stat",'<div class="v">'+s[0]+'</div><div class="k">'+s[1]+'</div>')); });
  })();

  /* ---- cuisines ---- */
  (function(){
    function build(box){
      if(!box) return;
      CUISINES.forEach(function(c){
        box.appendChild(el("div","cu",
          '<div class="cu-top">'+
            '<svg class="flag" viewBox="0 0 30 20" role="img" aria-label="'+c.country+'">'+FLAGS[c.flag]+'</svg>'+
            '<span class="country">'+c.n+'</span>'+
          '</div>'+
          svg(ICONS[c.icon]) +
          '<h4>'+c.title+'</h4>'+
          (c.desc ? '<p>'+c.desc+'</p>' : '')+
          (c.dishes ? '<div class="dishes">'+c.dishes.map(function(d){
            return '<span>'+d+'</span>'; }).join("")+'</div>' : '')));
      });
    }
    build($("#cuisines")); build($("#cuisines-2"));
  })();

  /* ---- tiers ---- */
  (function(){
    var tick='<path d="m4 12 5 5L20 6"/>';
    var box=$("#tiers");
    function tier(cls, label, price, blurb, lines){
      return el("div","tier"+(cls?" "+cls:""),
        '<div class="k">'+label+'</div><div class="amt">'+chf(price)+'</div>'+
        '<div class="per">per person</div>'+
        '<p class="blurb">'+blurb+'</p>'+
        '<ul>'+lines.map(function(t){ return '<li>'+svg(tick)+'<span>'+t+'</span></li>'; }).join("")+'</ul>');
    }
    box.appendChild(tier("", "Dinner", P_DINNER,
      "Everything we cook that night, and a seat at the table.",
      ["Everything we cook that evening",
       "Brought to the middle \u2014 help yourself",
       "A welcome drink when you walk in",
       "Water, coffee and tea",
       "Bring a bottle if you like \u2014 no corkage"]));
    box.appendChild(tier("hot", "Dinner with drinks", P_DRINKS,
      "The same table, with a glass in your hand from the moment you arrive.",
      ["Everything in the dinner, plus \u2014",
       "Wine from our own stock, matched to the food",
       "Gin and tonic",
       "Vodka soda"]));
  })();

  /* ---- evenings ---- */
  function evCard(ev, withMenu){
    var node = el("article","ev");
    node.innerHTML =
      '<div class="idx">'+ev.n+'</div>'+
      '<div class="body"><div class="when">'+ev.when+'</div>'+
        '<div class="ev-title">'+
          (ev.flag ? '<svg class="flag" viewBox="0 0 30 20" role="presentation">'+FLAGS[ev.flag]+'</svg>' : '')+
          '<h3>'+ev.title+'</h3>'+
        '</div>'+
        (ev.sub ? '<p>'+ev.sub+'</p>' : '')+
        (ev.dishes && !ev.menu ? '<div class="dishes">'+ev.dishes.map(function(d){return '<span>'+d+'</span>';}).join("")+'</div>' : '')+
      '</div>'+
      '<div class="right"><span class="chip '+ev.status+'">'+ev.statusText+'</span>'+
      '<a class="btn sm ghost" href="#/book" data-ev="'+ev.id+'" data-link><span>Join the list</span></a></div>';

    if (withMenu && (ev.menu || ev.courses.length)){
      var body = $(".body", node);
      var btn = el("button","mtoggle",'<span class="lbl">Read the menu</span>'+svg('<path d="m6 9 6 6 6-6"/>'));
      btn.setAttribute("aria-expanded","false");
      var ul = el("ul","courses"); ul.hidden = true;
      if (ev.menu) {
        ul.innerHTML = menuHTML(ev.menu);
      } else {
        ev.courses.forEach(function(c){
          ul.appendChild(el("li","",'<div class="nm">'+c[0]+'</div><p>'+c[1]+'</p>'));
        });
      }
      btn.addEventListener("click",function(){
        var open = btn.getAttribute("aria-expanded")==="true";
        btn.setAttribute("aria-expanded",String(!open));
        ul.hidden = open;
        $(".lbl",btn).textContent = open ? "Read the menu" : "Hide the menu";
      });
      body.appendChild(btn); node.appendChild(ul);
    }
    return node;
  }
  (function(){
    var all=$("#all-evenings"), home=$("#home-evenings");
    EVENINGS.forEach(function(ev,i){
      all.appendChild(evCard(ev,true));
      if(i<3) home.appendChild(evCard(ev,false));
    });
  })();

  /* ---- evenings we have already cooked, and what guests said ---- */
  (function(){
    var box=$("#past-evenings"), PHOTOS = window.EVENING_PHOTOS || {};
    if(box) PAST.forEach(function(p){
      var pic = PHOTOS[(p.photo||"").toLowerCase()];
      box.appendChild(el("article","past-card",
        '<div class="past-pic">' +
          (pic ? '<img src="'+pic+'" alt="'+p.title+' at our table" loading="lazy" decoding="async">'
               : '<div class="ph"><div class="lbl">Photo to come</div></div>') +
        '</div>' +
        '<div class="past-meta">' +
          '<svg class="flag" viewBox="0 0 30 20" role="presentation">'+FLAGS[p.flag]+'</svg>' +
          '<div><h3>'+p.title+'</h3>' +
          '<div class="when">'+p.date+' \u00b7 '+p.note+'</div></div>' +
        '</div>'));
    });

    var rbox=$("#reviews");
    if(rbox) REVIEWS.forEach(function(q){
      rbox.appendChild(el("blockquote","review",'<p>'+q+'</p>'));
    });
  })();

  /* ---- sample menu ---- */
  (function(){
    var box=$("#sample-menu"), ev=EVENINGS[0], head=$("#sample-title");
    if(head) head.textContent = plain(ev.title) + " \u00b7 " + ev.when;
    if (ev.menu) {
      box.innerHTML = menuHTML(ev.menu);
    } else {
      ev.courses.forEach(function(c){
        box.appendChild(el("li","",'<div class="nm">'+c[0]+'</div><p>'+c[1]+'</p>'));
      });
    }
  })();

  /* ---- timeline ---- */
  (function(){
    var box=$("#timeline");
    TIMELINE.forEach(function(t){
      var row=el("div","ev",'<div class="idx">'+t[0]+'</div><div><p style="color:var(--body)">'+t[1]+'</p></div>');
      row.style.gridTemplateColumns="90px 1fr";
      box.appendChild(row);
    });
  })();

  /* ---- FAQ ---- */
  (function(){
    var box=$("#faq");
    FAQ.forEach(function(q){
      box.appendChild(el("details","","<summary>"+q[0]+"</summary><div class=\"ans\"><p>"+q[1]+"</p></div>"));
    });
  })();

  /* ---- gallery + lightbox ----
     Sources, in order: the captioned GALLERY list (keyed images used elsewhere
     on the site), then anything dropped into assets/gallery/<name>/, which the
     build discovers on its own. Any remaining slots up to the target render as
     placeholders so the grid always reads as a finished wall. */
  var galItems=[];
  /* "Add a photo" tiles are a to-do list for us, not something a guest should
     ever see — so they only render while developing locally. */
  var DEV = /^(localhost|127\.|0\.0\.0\.0|\[::1\])$/.test(location.hostname) ||
            location.protocol === "file:";
  var CAM = '<rect x="3" y="6" width="18" height="14" rx="2"/><circle cx="12" cy="13" r="3.5"/><path d="M8 6l1.5-2h5L16 6"/>';

  function fillGrid(box, items, target, label, featureFirst){
    if(!box) return;
    items.forEach(function(it,i){
      var idx=galItems.length;
      galItems.push(it);
      var b=el("button", (featureFirst && i===0) ? "big" : "",
        '<img src="'+(it.thumb||it.src)+'" alt="'+(it.caption||"Basel Supper Club")+
        '" loading="lazy" decoding="async">');
      b.addEventListener("click",function(){ openLb(idx); });
      box.appendChild(b);
    });
    if(!DEV) return;
    for(var k=items.length; k<target; k++){
      box.appendChild(el("div","ph",
        '<div class="lbl">'+svg(CAM)+label+'</div>'));
    }
  }

  (function(){
    var G = window.GALLERIES || { food:[], guests:[] };

    // captioned images already used across the site
    var named = GALLERY.filter(function(g){ return !!IMAGES[g[0]]; })
                       .map(function(g){ return { src:IMAGES[g[0]], caption:g[1] }; });

    var food = named.concat(G.food || []);
    fillGrid($("#gal"), food, S.FOOD_SLOTS, "Add a food photo", true);
    fillGrid($("#gal-guests"), G.guests || [], S.GUEST_SLOTS, "Add a guest photo", false);
  })();

  var lbIdx=0, lb=$("#lb"), lbi=$("#lbi");
  function openLb(i){
    if(i<0) i=galItems.length-1; if(i>=galItems.length) i=0;
    lbIdx=i; lbi.src=galItems[i].src; lbi.alt=galItems[i].caption;
    lb.classList.add("on"); document.body.style.overflow="hidden";
    if(window.__track) window.__track("view_gallery_photo");
  }
  function closeLb(){ lb.classList.remove("on"); document.body.style.overflow=""; }
  $("#lbx").addEventListener("click",closeLb);
  $("#lbp").addEventListener("click",function(){ openLb(lbIdx-1); });
  $("#lbn").addEventListener("click",function(){ openLb(lbIdx+1); });
  lb.addEventListener("click",function(e){ if(e.target===lb) closeLb(); });
  document.addEventListener("keydown",function(e){
    if(!lb.classList.contains("on")) return;
    if(e.key==="Escape") closeLb();
    if(e.key==="ArrowLeft") openLb(lbIdx-1);
    if(e.key==="ArrowRight") openLb(lbIdx+1);
  });

  /* ---- booking form ---- */
  (function(){
    var form=$("#bookform"); if(!form) return;
    var sel=$("#f-evening");
    EVENINGS.forEach(function(ev){
      var o=document.createElement("option");
      o.value=ev.id; o.textContent=plain(ev.title)+" — "+ev.when;
      sel.appendChild(o);
    });
    function evById(id){ for(var i=0;i<EVENINGS.length;i++) if(EVENINGS[i].id===id) return EVENINGS[i]; return EVENINGS[0]; }
    function tier(){ return parseInt(form.querySelector('input[name="tier"]:checked').value,10); }
    function kind(){ return form.querySelector('input[name="kind"]:checked').value; }

    function recalc(){
      var seats=parseInt($("#f-seats").value,10)||1, t=tier();
      $("#s-l").textContent = seats+" × "+(t===P_DRINKS?"dinner with drinks":"dinner")+" ("+chf(t)+")";
      $("#s-v").textContent = chf(t*seats);
      $("#s-t").textContent = chf(t*seats);
    }
    $("#f-seats").addEventListener("change",recalc);
    $("#f-evening").addEventListener("change",recalc);
    $$('input[name="tier"]',form).forEach(function(r){ r.addEventListener("change",recalc); });
    recalc();

    function syncKind(){
      var k=kind();
      $("#seat-fields").hidden = k!=="seat";
      $("#private-fields").hidden = k!=="private";
      $("#review-fields").hidden = k!=="review";
      $(".btn span", form.querySelector('button[type="submit"]').parentNode) ;
      form.querySelector('button[type="submit"] span').textContent =
        k==="list" ? "Add me to the list"
        : k==="private" ? "Send the enquiry"
        : k==="review" ? "Send the review"
        : "Send the request";
    }
    $$('input[name="kind"]',form).forEach(function(r){ r.addEventListener("change",syncKind); });
    syncKind();

    document.addEventListener("click",function(e){
      var a=e.target.closest && e.target.closest("a[data-ev]");
      if(!a) return;
      form.querySelector('input[value="seat"]').checked=true; syncKind(); recalc();
    });

    /* The form posts to FormSubmit, which forwards to our inbox. No account,
       no server of our own. If the request fails for any reason the guest is
       offered a mailto with everything already written, so a submission is
       never simply lost. */
    var ENDPOINT = "https://formsubmit.co/ajax/verma.nikunj66@gmail.com";
    var submitBtn = form.querySelector('button[type="submit"]');

    var THANKS = {
      seat:    ["Your request is in.",
                "We read every one ourselves and put each table together by hand. You'll hear from us within 24 hours \u2014 and if there's room, we'll send a link to pay."],
      private: ["Thank you \u2014 we'll be in touch.",
                "We'll come back to you about the date, the guests and what you'd like on the table."],
      list:    ["You're on the list.",
                "You'll hear about new dates before they go public. Not often, and never anything else."],
      review:  ["Thank you for writing.",
                "We read every one. If it goes on the site, it goes up word for word \u2014 credited the way you asked."]
    };

    /* Replace the whole card, not just the form. Leaving the intro above the
       thank-you meant the page promised a reply twice in a row. */
    function showThanks(k){
      var t = THANKS[k] || THANKS.list;
      var panel = el("div","thanks",
        '<svg class="ic" viewBox="0 0 24 24"><path d="m4 12 5 5L20 6"/></svg>' +
        '<h2>'+t[0]+'</h2><p>'+t[1]+'</p>');
      var close = el("button","btn ghost","<span>Close</span>");
      close.type = "button";
      close.addEventListener("click", function(){ closeBook(); });
      panel.appendChild(close);

      var card = form.closest(".modal-scroll") || form.parentNode;
      card.innerHTML = "";
      card.appendChild(panel);
    }

    function mailtoFallback(subject, body){
      return "mailto:verma.nikunj66@gmail.com?subject=" +
        encodeURIComponent(subject) + "&body=" + encodeURIComponent(body);
    }

    form.addEventListener("submit",function(e){
      e.preventDefault();
      $("#w-name").classList.remove("bad"); $("#w-email").classList.remove("bad");
      $("#e-name").textContent=""; $("#e-email").textContent="";
      $("#e-agree").textContent="";
      var name=$("#f-name").value.trim(), email=$("#f-email").value.trim(), ok=true;
      if(!name){ $("#w-name").classList.add("bad"); $("#e-name").textContent="We'd like to know who's coming."; ok=false; }
      if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)){
        $("#w-email").classList.add("bad"); $("#e-email").textContent="We need a working email to reply to."; ok=false; }
      if(kind()!=="review" && (!$("#f-privacy").checked || !$("#f-terms").checked)){
        $("#e-agree").textContent="Please tick both boxes above so we can take your booking.";
        ok=false;
      }
      if(!ok){ (name?$("#f-email"):$("#f-name")).focus(); return; }

      var k=kind(), subject, fields={};
      fields["Name"]=name;
      fields["Email"]=email;
      if($("#f-phone").value.trim()) fields["Phone"]=$("#f-phone").value.trim();

      if(k==="seat"){
        var ev=evById(sel.value), seats=parseInt($("#f-seats").value,10)||1, t=tier();
        subject="Seat request \u2014 "+plain(ev.title);
        fields["Evening"]=plain(ev.title)+" ("+ev.when+")";
        fields["Seats"]=String(seats);
        fields["Option"]=(t===P_DRINKS?"Dinner with drinks (CHF 150 each)":"Dinner (CHF 120 each)");
        fields["Total if confirmed"]=chf(t*seats);
      } else if(k==="private"){
        subject="Private dining enquiry \u2014 "+name;
        fields["Date in mind"]=$("#f-pdate").value.trim()||"not sure yet";
        fields["Guests"]=$("#f-pguests").value.trim()||"not sure yet";
        fields["Where"]=$("#f-pwhere").value.trim()||"not sure yet";
      } else if(k==="review"){
        subject="Review \u2014 "+name;
        fields["Evening"]=$("#f-which").value.trim()||"not given";
        fields["Credit to"]=$("#f-credit").value.trim()||"not given";
        fields["Review"]=$("#f-review").value.trim()||"(empty)";
      } else {
        subject="Mailing list \u2014 "+name;
        fields["Request"]="Please add me to the list for new dates.";
      }
      if(k!=="review"){
        fields["Allergies / dietary"]=$("#f-diet").value.trim()||"none given";
        fields["Newsletter"]=$("#f-news").checked?"yes please":"no";
      }
      var note=$("#f-note").value.trim();
      if(note) fields["Notes"]=note;

      var body = Object.keys(fields).map(function(key){
        return key+": "+fields[key];
      }).join("\n") + "\n\n\u2014 sent from baselsupperclub.ch";

      var payload = { _subject: subject, _template: "table", _captcha: "false" };
      Object.keys(fields).forEach(function(key){ payload[key]=fields[key]; });

      submitBtn.disabled = true;
      $("span", submitBtn).textContent = "Sending\u2026";

      fetch(ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify(payload)
      }).then(function(res){ return res.json(); })
        .then(function(data){
          if(String(data.success) !== "true") throw new Error(data.message || "rejected");
          if(window.__track) window.__track("generate_lead", {
            request_type: k,
            value: k==="seat" ? tier()*(parseInt($("#f-seats").value,10)||1) : undefined,
            currency: "CHF"
          });
          showThanks(k);
        })
        .catch(function(){
          submitBtn.disabled = false;
          $("span", submitBtn).textContent = "Try again";
          $("#e-agree").innerHTML =
            'That did not go through. Please <a href="' +
            mailtoFallback(subject, body) +
            '" style="color:var(--accent)">send it by email instead</a> \u2014 everything is already written.';
        });
    });
  })();

  /* ---- nav dropdowns ---- */
  $$("[data-drop]").forEach(function(item){
    var btn=item.querySelector("button");
    btn.addEventListener("click",function(e){
      e.stopPropagation();
      var open=item.classList.contains("open");
      $$("[data-drop]").forEach(function(o){ o.classList.remove("open"); o.querySelector("button").setAttribute("aria-expanded","false"); });
      if(!open){ item.classList.add("open"); btn.setAttribute("aria-expanded","true"); }
    });
    item.addEventListener("mouseenter",function(){
      if(window.matchMedia("(min-width:861px)").matches){ item.classList.add("open"); btn.setAttribute("aria-expanded","true"); }
    });
    item.addEventListener("mouseleave",function(){
      if(window.matchMedia("(min-width:861px)").matches){ item.classList.remove("open"); btn.setAttribute("aria-expanded","false"); }
    });
  });
  document.addEventListener("click",function(){
    $$("[data-drop]").forEach(function(o){ o.classList.remove("open"); o.querySelector("button").setAttribute("aria-expanded","false"); });
  });

  /* ---- mobile sheet ---- */
  var sheet=$("#sheet");
  $("#burger").addEventListener("click",function(){ sheet.classList.add("on"); document.body.style.overflow="hidden"; });
  $("#sheetx").addEventListener("click",closeSheet);
  function closeSheet(){ sheet.classList.remove("on"); document.body.style.overflow=""; }

  /* ---- hide top bar on scroll down ---- */
  (function(){
    var last=0, top=$("#top");
    window.addEventListener("scroll",function(){
      var y=window.scrollY;
      if(y>240 && y>last) top.classList.add("hide"); else top.classList.remove("hide");
      last=y;
    },{passive:true});
  })();

  /* ---- scroll reveal (fails safe: no JS = everything visible) ---- */
  (function(){
    if(!("IntersectionObserver" in window)) return;
    if(window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    document.documentElement.classList.add("js-rv");
    var io=new IntersectionObserver(function(entries){
      entries.forEach(function(en){
        if(en.isIntersecting){ en.target.classList.add("in"); io.unobserve(en.target); }
      });
    },{rootMargin:"0px 0px -8% 0px", threshold:.06});
    function watch(root){
      $$(".rv",root).forEach(function(n){
        if(n.classList.contains("in")) return;
        // anything already on screen is shown immediately, never animated in
        if(n.getBoundingClientRect().top < window.innerHeight * 0.95){ n.classList.add("in"); return; }
        io.observe(n);
      });
    }
    window.__watchReveal=watch;
    watch(document);
    // safety net — nothing stays invisible waiting on an observer
    setTimeout(function(){ $$(".rv").forEach(function(n){ n.classList.add("in"); }); },1200);
  })();


  /* ---- reservation modal ----
     #/book is a modal over whatever page you were on, so closing it puts you
     back where you were rather than dumping you on the home page. */
  var bookModal=$("#bookmodal"), lastPath="/", bookOpen=false, lastFocus=null;

  function openBook(){
    if(bookOpen) return;
    bookOpen=true; lastFocus=document.activeElement;
    bookModal.hidden=false;
    document.body.style.overflow="hidden";
    if(window.__track) window.__track("booking_open");
    var first=bookModal.querySelector("input,select,textarea,button");
    if(first) setTimeout(function(){ first.focus(); },80);
  }
  function closeBook(silent){
    if(!bookOpen) return;
    bookOpen=false;
    bookModal.hidden=true;
    document.body.style.overflow="";
    if(lastFocus && lastFocus.focus) lastFocus.focus();
    if(!silent && (location.hash||"").replace(/^#/,"")==="/book"){
      location.hash="#"+lastPath;
    }
  }
  $("#bookx").addEventListener("click",function(){ closeBook(); });
  $("#bookcancel").addEventListener("click",function(){ closeBook(); });
  bookModal.addEventListener("click",function(e){ if(e.target===bookModal) closeBook(); });
  document.addEventListener("keydown",function(e){
    if(e.key==="Escape" && bookOpen && !lb.classList.contains("on")) closeBook();
  });

  /* ---- router with a curtain wipe ---- */
  var ROUTES={ "/":"v-home","/evenings":"v-evenings","/menus":"v-menus","/gallery":"v-gallery",
               "/private":"v-private","/about":"v-about","/space":"v-space",
               "/faq":"v-faq","/legal":"v-legal" };
  var curtain=$("#curtain"), first=true;

  function paint(path){
    Object.keys(ROUTES).forEach(function(p){
      document.getElementById(ROUTES[p]).hidden = (p!==path);
    });
    $$("nav.mainnav a[data-link]").forEach(function(a){
      a.classList.toggle("on", a.getAttribute("href")==="#"+path && !a.classList.contains("btn"));
    });
    window.scrollTo(0,0);
    if(window.__watchReveal) window.__watchReveal(document.getElementById(ROUTES[path]));
  }

  function route(){
    var path=(location.hash||"#/").replace(/^#/,"");
    closeSheet();

    if(path==="/book"){
      if(first){ first=false; paint(lastPath); }   // deep link straight to #/book
      openBook();
      return;
    }

    closeBook(true);
    if(!ROUTES[path]) path="/";
    lastPath=path;
    if(first || window.matchMedia("(prefers-reduced-motion: reduce)").matches){
      first=false; paint(path); return;
    }
    curtain.classList.remove("in"); void curtain.offsetWidth; curtain.classList.add("in");
    setTimeout(function(){ paint(path); }, 340);
  }
  window.addEventListener("hashchange",route);

  if(!DEV){
    $$(".ph").forEach(function(n){
      var parent=n.parentNode;
      parent.removeChild(n);
      // a 2-up grid left holding one photo should stop being a 2-up grid
      if(parent.children.length===1 && /1fr 1fr/.test(parent.style.gridTemplateColumns)){
        parent.style.gridTemplateColumns="1fr";
      }
    });
  }

  /* ---- analytics consent + the handful of events worth measuring ---- */
  var track = (function(){
    var KEY="bsc-consent", bar=$("#consent");
    function stored(){ try{ return localStorage.getItem(KEY); }catch(e){ return null; } }
    function choose(v){
      try{ localStorage.setItem(KEY,v); }catch(e){}
      if(window.gtag) gtag("consent","update",{ analytics_storage: v==="granted" ? "granted" : "denied" });
      if(bar) bar.hidden = true;
    }
    if(bar && window.gtag && !stored()) bar.hidden = false;
    if(bar){
      $("#consent-yes").addEventListener("click",function(){ choose("granted"); });
      $("#consent-no").addEventListener("click",function(){ choose("denied"); });
    }
    return function(name, params){
      if(window.gtag) gtag("event", name, params || {});
    };
  })();
  window.__track = track;

  $("#yr").textContent=new Date().getFullYear();
  route();
})();
