/* ── Basel Supper Club — rendering, router, booking form ──
   Reads window.SITE (content.js) and window.IMAGES (generated by build.mjs). */
(function () {
  "use strict";

  var S = window.SITE;
  var P_DINNER = S.P_DINNER, P_DRINKS = S.P_DRINKS;
  var CUISINES = S.CUISINES, FLAGS = S.FLAGS, EVENINGS = S.EVENINGS;
  var TIMELINE = S.TIMELINE, FAQ = S.FAQ, GALLERY = S.GALLERY, ICONS = S.ICONS;

  var $ = function(s,r){ return (r||document).querySelector(s); };
  var $$ = function(s,r){ return Array.prototype.slice.call((r||document).querySelectorAll(s)); };
  function el(t,c,h){ var n=document.createElement(t); if(c)n.className=c; if(h!=null)n.innerHTML=h; return n; }
  function chf(n){ return "CHF "+n.toLocaleString("de-CH"); }
  function plain(s){ return s.replace(/&amp;/g,"&"); }
  function svg(p,cls){ return '<svg class="ic '+(cls||"")+'" viewBox="0 0 24 24">'+p+'</svg>'; }

  /* ---- wire up the photos ---- */
  $$("[data-img]").forEach(function(n){
    var k = n.getAttribute("data-img");
    if (IMAGES[k]) { n.src = IMAGES[k]; n.loading = "lazy"; }
  });
  $$("[data-bg]").forEach(function(n){
    var k = n.getAttribute("data-bg");
    if (IMAGES[k]) n.style.backgroundImage = 'url("'+IMAGES[k]+'")';
  });

  /* ---- marquee ---- */
  (function(){
    var words = ["Ramen","Tantan","Curry","Gyoza","Pasta","Thai","Tacos","Paneer","Dumplings","Chilli oil","Mezze","Ragù"];
    var run = words.map(function(w){ return '<span>'+w+'<i></i></span>'; }).join("");
    $("#marq").innerHTML = run + run;
  })();

  /* ---- stats ---- */
  (function(){
    var S=[["6–8","Seats at the table"],["40+","Countries on the menu"],["120","CHF per person"],["1","Long table"]];
    var box=$("#stats");
    S.forEach(function(s){ box.appendChild(el("div","stat",'<div class="v">'+s[0]+'</div><div class="k">'+s[1]+'</div>')); });
  })();

  /* ---- cuisines ---- */
  (function(){
    function build(box){
      if(!box) return;
      CUISINES.forEach(function(c){
        box.appendChild(el("div","cu",
          '<div class="cu-top">'+
            '<svg class="flag" viewBox="0 0 30 20" role="img" aria-label="'+c.country+'">'+FLAGS[c.flag]+'</svg>'+
            '<span class="country">'+c.n+' \u00b7 '+c.country+'</span>'+
          '</div>'+
          svg(ICONS[c.icon]) +
          '<h4>'+c.title+'</h4><p>'+c.desc+'</p>'+
          '<div class="dishes">'+c.dishes.map(function(d){ return '<span>'+d+'</span>'; }).join("")+'</div>'));
      });
    }
    build($("#cuisines")); build($("#cuisines-2"));
  })();

  /* ---- tiers ---- */
  (function(){
    var tick='<path d="m4 12 5 5L20 6"/>';
    var box=$("#tiers");
    box.appendChild(el("div","tier",
      '<div class="k">Dinner</div><div class="amt">'+chf(P_DINNER)+'</div><div class="per">per person</div>'+
      '<ul>'+
      ['A full table of food \u2014 however many dishes that takes','Served in the middle, help yourself','Welcome drink on arrival','Water, still and sparkling, all evening',
       'Coffee and tea','Bring your own bottle — no corkage']
      .map(function(t){ return '<li>'+svg(tick)+'<span>'+t+'</span></li>'; }).join("")+'</ul>'));
    box.appendChild(el("div","tier hot",
      '<div class="k">Dinner with drinks</div><div class="amt">'+chf(P_DRINKS)+'</div><div class="per">per person</div>'+
      '<ul>'+
      ['Everything in the first, plus —','Wine, chosen against the courses','Beer, and gin &amp; tonic',
       'Vodka mate and classic cocktails','Poured all evening, no tab at the end']
      .map(function(t){ return '<li>'+svg(tick)+'<span>'+t+'</span></li>'; }).join("")+'</ul>'));
  })();

  /* ---- evenings ---- */
  function evCard(ev, withMenu){
    var node = el("article","ev");
    node.innerHTML =
      '<div class="idx">'+ev.n+'</div>'+
      '<div class="body"><div class="when">'+ev.when+'</div>'+
        '<div class="ev-title">'+
          (ev.flag ? '<svg class="flag" viewBox="0 0 30 20" role="presentation">'+FLAGS[ev.flag]+'</svg>' : '')+
          '<h3>'+ev.title+'</h3>'+
        '</div>'+
        '<p>'+ev.sub+'</p>'+
        (ev.dishes ? '<div class="dishes">'+ev.dishes.map(function(d){return '<span>'+d+'</span>';}).join("")+'</div>' : '')+
      '</div>'+
      '<div class="right"><span class="chip '+ev.status+'">'+ev.statusText+'</span>'+
      '<a class="btn sm ghost" href="#/book" data-ev="'+ev.id+'" data-link><span>Join the list</span></a></div>';

    if (withMenu && ev.courses.length){
      var body = $(".body", node);
      var btn = el("button","mtoggle",'<span class="lbl">Read the menu</span>'+svg('<path d="m6 9 6 6 6-6"/>'));
      btn.setAttribute("aria-expanded","false");
      var ul = el("ul","courses"); ul.hidden = true;
      ev.courses.forEach(function(c){
        ul.appendChild(el("li","",'<div class="nm">'+c[0]+'</div><p>'+c[1]+'</p>'));
      });
      btn.addEventListener("click",function(){
        var open = btn.getAttribute("aria-expanded")==="true";
        btn.setAttribute("aria-expanded",String(!open));
        ul.hidden = open;
        $(".lbl",btn).textContent = open ? "Read the menu" : "Hide the menu";
      });
      body.appendChild(btn); body.appendChild(ul);
    }
    return node;
  }
  (function(){
    var all=$("#all-evenings"), home=$("#home-evenings");
    EVENINGS.forEach(function(ev,i){
      all.appendChild(evCard(ev,true));
      if(i<3) home.appendChild(evCard(ev,false));
    });
  })();

  /* ---- sample menu ---- */
  (function(){
    var box=$("#sample-menu"), ev=EVENINGS[0];
    ev.courses.forEach(function(c){
      box.appendChild(el("li","",'<div class="nm">'+c[0]+'</div><p>'+c[1]+'</p>'));
    });
  })();

  /* ---- timeline ---- */
  (function(){
    var box=$("#timeline");
    TIMELINE.forEach(function(t){
      var row=el("div","ev",'<div class="idx">'+t[0]+'</div><div><p style="color:var(--body)">'+t[1]+'</p></div>');
      row.style.gridTemplateColumns="90px 1fr";
      box.appendChild(row);
    });
  })();

  /* ---- FAQ ---- */
  (function(){
    var box=$("#faq");
    FAQ.forEach(function(q){
      box.appendChild(el("details","","<summary>"+q[0]+"</summary><div class=\"ans\"><p>"+q[1]+"</p></div>"));
    });
  })();

  /* ---- gallery + lightbox ---- */
  var galItems=[];
  (function(){
    var box=$("#gal");
    GALLERY.forEach(function(g,i){
      if(!IMAGES[g[0]]) return;
      galItems.push(g);
      var b=el("button", i===0?"big":"", '<img src="'+IMAGES[g[0]]+'" alt="'+g[1]+'" loading="lazy">');
      b.addEventListener("click",function(){ openLb(galItems.indexOf(g)); });
      box.appendChild(b);
    });
    // a couple of slots for photos they'll add later
    for(var k=0;k<2;k++){
      box.appendChild(el("div","ph",'<div class="lbl">'+
        svg('<rect x="3" y="6" width="18" height="14" rx="2"/><circle cx="12" cy="13" r="3.5"/><path d="M8 6l1.5-2h5L16 6"/>')+
        'Add a photo</div>'));
    }
  })();

  var lbIdx=0, lb=$("#lb"), lbi=$("#lbi");
  function openLb(i){
    if(i<0) i=galItems.length-1; if(i>=galItems.length) i=0;
    lbIdx=i; lbi.src=IMAGES[galItems[i][0]]; lbi.alt=galItems[i][1];
    lb.classList.add("on"); document.body.style.overflow="hidden";
  }
  function closeLb(){ lb.classList.remove("on"); document.body.style.overflow=""; }
  $("#lbx").addEventListener("click",closeLb);
  $("#lbp").addEventListener("click",function(){ openLb(lbIdx-1); });
  $("#lbn").addEventListener("click",function(){ openLb(lbIdx+1); });
  lb.addEventListener("click",function(e){ if(e.target===lb) closeLb(); });
  document.addEventListener("keydown",function(e){
    if(!lb.classList.contains("on")) return;
    if(e.key==="Escape") closeLb();
    if(e.key==="ArrowLeft") openLb(lbIdx-1);
    if(e.key==="ArrowRight") openLb(lbIdx+1);
  });

  /* ---- booking form ---- */
  (function(){
    var form=$("#bookform"); if(!form) return;
    var sel=$("#f-evening");
    EVENINGS.forEach(function(ev){
      var o=document.createElement("option");
      o.value=ev.id; o.textContent=plain(ev.title)+" — "+ev.when;
      sel.appendChild(o);
    });
    function tier(){ return parseInt(form.querySelector('input[name="tier"]:checked').value,10); }
    function kind(){ return form.querySelector('input[name="kind"]:checked').value; }
    function evById(id){ for(var i=0;i<EVENINGS.length;i++) if(EVENINGS[i].id===id) return EVENINGS[i]; return EVENINGS[0]; }

    function recalc(){
      var seats=parseInt($("#f-seats").value,10)||1, t=tier();
      $("#s-l").textContent = seats+" × "+(t===P_DRINKS?"dinner with drinks":"dinner")+" ("+chf(t)+")";
      $("#s-v").textContent = chf(t*seats);
      $("#s-t").textContent = chf(t*seats);
    }
    $("#f-seats").addEventListener("change",recalc);
    $$('input[name="tier"]',form).forEach(function(r){ r.addEventListener("change",recalc); });
    recalc();

    function syncKind(){
      var k=kind();
      $("#seat-fields").hidden = k!=="seat";
      $("#private-fields").hidden = k!=="private";
      $(".btn span", form.querySelector('button[type="submit"]').parentNode) ;
      form.querySelector('button[type="submit"] span').textContent =
        k==="list" ? "Add me to the list" : k==="private" ? "Send the enquiry" : "Send the request";
    }
    $$('input[name="kind"]',form).forEach(function(r){ r.addEventListener("change",syncKind); });
    syncKind();

    document.addEventListener("click",function(e){
      var a=e.target.closest && e.target.closest("a[data-ev]");
      if(!a) return;
      form.querySelector('input[value="seat"]').checked=true; syncKind();
      sel.value=a.getAttribute("data-ev"); recalc();
    });

    form.addEventListener("submit",function(e){
      e.preventDefault();
      $("#w-name").classList.remove("bad"); $("#w-email").classList.remove("bad");
      $("#e-name").textContent=""; $("#e-email").textContent="";
      var name=$("#f-name").value.trim(), email=$("#f-email").value.trim(), ok=true;
      if(!name){ $("#w-name").classList.add("bad"); $("#e-name").textContent="We'd like to know who's coming."; ok=false; }
      if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)){
        $("#w-email").classList.add("bad"); $("#e-email").textContent="We need a working email to send the address to."; ok=false; }
      if(!ok){ (name?$("#f-email"):$("#f-name")).focus(); return; }

      var k=kind(), L=[], subject;
      L.push("Name: "+name); L.push("Email: "+email);
      if($("#f-phone").value.trim()) L.push("Phone: "+$("#f-phone").value.trim());
      L.push("");
      if(k==="seat"){
        var ev=evById(sel.value), seats=parseInt($("#f-seats").value,10)||1, t=tier();
        subject="Reservation — "+plain(ev.title);
        L.push("Evening: "+plain(ev.title)+" ("+ev.when+")");
        L.push("Seats: "+seats);
        L.push("Option: "+(t===P_DRINKS?"Dinner with drinks (CHF 150 each)":"Dinner (CHF 120 each)"));
        L.push("Total: "+chf(t*seats));
      } else if(k==="private"){
        subject="Private dining enquiry — "+name;
        L.push("Date in mind: "+($("#f-pdate").value.trim()||"not sure yet"));
        L.push("Guests: "+($("#f-pguests").value.trim()||"not sure yet"));
        L.push("Where: "+($("#f-pwhere").value.trim()||"not sure yet"));
      } else {
        subject="Mailing list — "+name;
        L.push("Please add me to the list for new dates.");
      }
      L.push("");
      L.push("Allergies / dietary: "+($("#f-diet").value.trim()||"none given"));
      var note=$("#f-note").value.trim();
      if(note){ L.push(""); L.push("Notes: "+note); }
      L.push(""); L.push("— sent from baselsupperclub.ch");

      window.location.href="mailto:hello@baselsupperclub.ch?subject="+
        encodeURIComponent(subject)+"&body="+encodeURIComponent(L.join("\n"));
    });
  })();

  /* ---- nav dropdowns ---- */
  $$("[data-drop]").forEach(function(item){
    var btn=item.querySelector("button");
    btn.addEventListener("click",function(e){
      e.stopPropagation();
      var open=item.classList.contains("open");
      $$("[data-drop]").forEach(function(o){ o.classList.remove("open"); o.querySelector("button").setAttribute("aria-expanded","false"); });
      if(!open){ item.classList.add("open"); btn.setAttribute("aria-expanded","true"); }
    });
    item.addEventListener("mouseenter",function(){
      if(window.matchMedia("(min-width:861px)").matches){ item.classList.add("open"); btn.setAttribute("aria-expanded","true"); }
    });
    item.addEventListener("mouseleave",function(){
      if(window.matchMedia("(min-width:861px)").matches){ item.classList.remove("open"); btn.setAttribute("aria-expanded","false"); }
    });
  });
  document.addEventListener("click",function(){
    $$("[data-drop]").forEach(function(o){ o.classList.remove("open"); o.querySelector("button").setAttribute("aria-expanded","false"); });
  });

  /* ---- mobile sheet ---- */
  var sheet=$("#sheet");
  $("#burger").addEventListener("click",function(){ sheet.classList.add("on"); document.body.style.overflow="hidden"; });
  $("#sheetx").addEventListener("click",closeSheet);
  function closeSheet(){ sheet.classList.remove("on"); document.body.style.overflow=""; }

  /* ---- hide top bar on scroll down ---- */
  (function(){
    var last=0, top=$("#top");
    window.addEventListener("scroll",function(){
      var y=window.scrollY;
      if(y>240 && y>last) top.classList.add("hide"); else top.classList.remove("hide");
      last=y;
    },{passive:true});
  })();

  /* ---- scroll reveal (fails safe: no JS = everything visible) ---- */
  (function(){
    if(!("IntersectionObserver" in window)) return;
    if(window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    document.documentElement.classList.add("js-rv");
    var io=new IntersectionObserver(function(entries){
      entries.forEach(function(en){
        if(en.isIntersecting){ en.target.classList.add("in"); io.unobserve(en.target); }
      });
    },{rootMargin:"0px 0px -8% 0px", threshold:.06});
    function watch(root){
      $$(".rv",root).forEach(function(n){
        if(n.classList.contains("in")) return;
        // anything already on screen is shown immediately, never animated in
        if(n.getBoundingClientRect().top < window.innerHeight * 0.95){ n.classList.add("in"); return; }
        io.observe(n);
      });
    }
    window.__watchReveal=watch;
    watch(document);
    // safety net — nothing stays invisible waiting on an observer
    setTimeout(function(){ $$(".rv").forEach(function(n){ n.classList.add("in"); }); },1200);
  })();

  /* ---- router with a curtain wipe ---- */
  var ROUTES={ "/":"v-home","/evenings":"v-evenings","/menus":"v-menus","/gallery":"v-gallery",
               "/private":"v-private","/about":"v-about","/space":"v-space","/book":"v-book",
               "/faq":"v-faq","/legal":"v-legal" };
  var curtain=$("#curtain"), first=true;

  function paint(path){
    Object.keys(ROUTES).forEach(function(p){
      document.getElementById(ROUTES[p]).hidden = (p!==path);
    });
    $$("nav.mainnav a[data-link]").forEach(function(a){
      a.classList.toggle("on", a.getAttribute("href")==="#"+path && !a.classList.contains("btn"));
    });
    window.scrollTo(0,0);
    if(window.__watchReveal) window.__watchReveal(document.getElementById(ROUTES[path]));
  }

  function route(){
    var path=(location.hash||"#/").replace(/^#/,"");
    if(!ROUTES[path]) path="/";
    closeSheet();
    if(first || window.matchMedia("(prefers-reduced-motion: reduce)").matches){
      first=false; paint(path); return;
    }
    curtain.classList.remove("in"); void curtain.offsetWidth; curtain.classList.add("in");
    setTimeout(function(){ paint(path); }, 340);
  }
  window.addEventListener("hashchange",route);

  /* ---- TEMPORARY font chooser ---- */
  (function(){
    var pick=$("#fontpick"); if(!pick) return;
    var btns=$$("button",pick), saved="fraunces";
    try{ saved = localStorage.getItem("bsc-font") || "fraunces"; }catch(e){}
    function apply(f){
      document.documentElement.setAttribute("data-font",f);
      btns.forEach(function(b){ b.setAttribute("aria-pressed", String(b.getAttribute("data-f")===f)); });
      try{ localStorage.setItem("bsc-font",f); }catch(e){}
    }
    btns.forEach(function(b){ b.addEventListener("click",function(){ apply(b.getAttribute("data-f")); }); });
    apply(saved);
  })();

  $("#yr").textContent=new Date().getFullYear();
  route();
})();
